[customizations.installer.kickstart]
contents = """
lang en_US.UTF-8
keyboard us
timezone UTC

network --bootproto=dhcp --device=link --activate --onboot=on

# IMPORTANT:
# No clearpart
# No zerombr
# No autopart
# No ignoredisk
#
# Storage must be selected interactively by the user.
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Payloads",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]

disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription"
]
